services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: flakyhunter
      POSTGRES_USER: flakyuser
      POSTGRES_PASSWORD: flakypass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flakyuser"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: ghcr.io/bogomolovvm/flakyhunter:latest
    ports:
      - "8000:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/flakyhunter
      SPRING_DATASOURCE_USERNAME: flakyuser
      SPRING_DATASOURCE_PASSWORD: flakypass
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: